module.exports = {
AWS_ACCESS_KEY:process.env.AWS_ACCESS_KEY,
AWS_SECRET_ACCESS_KEY:process.env.AWS_SECRET_ACCESS_KEY,
GOOGLEID:process.env.GOOGLEID,
GOOGLE_SECRET:process.env.GOOGLE_SECRET,
YAHOOID:process.env.YAHOOID,
YAHOO_SECRET:process.env.YAHOO_SECRET,
STRIPE_CONNECT:process.env.STRIPE_CONNECT,
STRIPE_SECRET:process.env.STRIPE_SECRET,
SERVER_API:process.env.SERVER_API
}